#!/usr/bin/env python3
"""Embed starter text files into a deterministic, stock Bash 3.2 installer.

Developer command: python3 scripts/build-operations-installer.py
No Python, Git, or template downloads are needed by the generated installer.
"""

import argparse
import hashlib
import os
from pathlib import Path
import shlex
import stat
import tempfile


ROOT = Path(__file__).resolve().parents[1]
HEADER = r'''#!/bin/bash
# Generated by scripts/build-operations-installer.py; edit starter/ and rebuild.
# Stock macOS Bash 3.2; no Python or Git runtime required.
# Download completely and check curl succeeds before executing this script.
# Piped stdin is supported; the script cannot verify an upstream curl exit code.
main() {
    set -euo pipefail
    local destination="${HOME:?HOME must be set}/Documents/AI Operations"
    local no_open=0 with_mangomagic=0 no_restart=0 created=0 preserved=0

    fail() { printf 'Setup stopped: %s\n' "$*" >&2; exit 1; }
    usage() {
        cat <<'OPERATIONS_USAGE'
Create a local AI Operations starter folder. Existing files are preserved.

Usage: /bin/bash setup-operations.sh [--destination PATH] [--no-open]
                                   [--with-mangomagic [--no-restart]]
       /bin/bash -s -- [options] < downloaded-setup.sh

  --destination PATH  Folder to populate (default: $HOME/Documents/AI Operations).
  --no-open           Do not open the folder in Finder.
  --with-mangomagic   Also install MangoMagic 7.1, register it and restart ChatGPT.
  --no-restart        With --with-mangomagic, defer the ChatGPT restart.
  --help              Show this help without making changes.

Without --with-mangomagic this creates local files only. Add the folder as a
local project in the app, then paste the onboarding prompt from START_HERE.md
into a new task in that project.
OPERATIONS_USAGE
    }
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --destination)
                [ "$#" -ge 2 ] || fail '--destination requires a path.'
                [ -n "$2" ] || fail '--destination requires a non-empty path.'
                case "$2" in --*) fail '--destination requires a path, not an option.' ;; esac
                destination=$2; shift 2 ;;
            --no-open) no_open=1; shift ;;
            --with-mangomagic) with_mangomagic=1; shift ;;
            --no-restart) no_restart=1; shift ;;
            --help) usage; return 0 ;;
            *) fail "Unknown option: $1 (use --help)." ;;
        esac
    done
    local gold='' bold='' reset=''
    if [ -t 1 ] && [ -z "${NO_COLOR+x}" ]; then
        gold=$'\033[38;5;214m'; bold=$'\033[1m'; reset=$'\033[0m'
    fi
    printf '\n%s  +--------------------------------------------------+%s\n' "$gold" "$reset"
    printf '%s%s    ManyMangoes%s\n' "$gold" "$bold" "$reset"
    printf '    Data + AI + Automation\n'
    printf '    AI Operations | Your local workspace\n'
    printf '%s  +--------------------------------------------------+%s\n\n' "$gold" "$reset"
    case "$destination" in /*) ;; *) destination="$PWD/$destination" ;; esac
    # Strip trailing slashes and /., which otherwise hide a symlink root.
    while [ "$destination" != / ]; do
        case "$destination" in
            */) destination=${destination%/} ;;
            */.) destination=${destination%/.} ;;
            *) break ;;
        esac
    done

    check_directory() {
        local path=$1
        [ ! -L "$path" ] || fail "Symlink directory refused: $path"
        if [ -e "$path" ] && [ ! -d "$path" ]; then
            fail "Not a directory: $path"
        fi
    }
    check_parents() {
        local relative=$1 path="$destination" component
        check_directory "$path"
        while [ -n "$relative" ]; do
            component=${relative%%/*}
            path="$path/$component"
            check_directory "$path"
            case "$relative" in */*) relative=${relative#*/} ;; *) break ;; esac
        done
    }
    check_file() {
        local relative=$1 path="$destination/$1"
        case "$relative" in */*) check_parents "${relative%/*}" ;; *) check_parents '' ;; esac
        [ ! -L "$path" ] || fail "Symlink file refused: $path"
        if [ -e "$path" ] && [ ! -f "$path" ]; then
            fail "Not a regular file: $path"
        fi
    }
    ensure_directory() {
        check_parents "$1"
        mkdir -p -- "$destination/$1" || fail "Cannot create directory: $destination/$1"
    }
    write_file() {
        local relative=$1 executable=$2 final_newline=$3
        local path="$destination/$1"
        check_file "$relative"
        if [ -f "$path" ]; then
            preserved=$((preserved + 1))
            return 0
        fi
        # Quoted heredocs supply literal data. The loop also preserves files
        # lacking a final newline, without eval or command substitution.
        # Stage on the same filesystem. Only a complete, permissioned file is
        # published. Stock macOS link uses the exact target (unlike ln, which
        # can put the file INSIDE a raced directory), and never overwrites it.
        if ! (
            temporary=''
            cleanup_temp() {
                local status=$?
                trap - EXIT
                if [ -n "$temporary" ]; then
                    if ! rm -f -- "$temporary"; then
                        printf 'Cannot remove temporary file: %s\n' "$temporary" >&2
                        [ "$status" -ne 0 ] || status=1
                    fi
                fi
                exit "$status"
            }
            trap cleanup_temp EXIT
            trap 'exit 130' INT
            trap 'exit 143' TERM
            temporary=$(mktemp "${path%/*}/.operations-setup.XXXXXXXX") || exit 1
            emit_text() {
                local line first=1
                while IFS= read -r line; do
                    if [ "$first" -eq 0 ]; then printf '\n' || return 1; fi
                    printf '%s' "$line" || return 1
                    first=0
                done
                if [ "$final_newline" -eq 1 ]; then printf '\n' || return 1; fi
                return 0
            }
            emit_text > "$temporary" || exit 1
            if [ "$executable" -eq 1 ]; then
                chmod 755 "$temporary" || exit 1
            else
                chmod 644 "$temporary" || exit 1
            fi
            check_file "$relative"
            [ ! -e "$path" ] || fail "Destination appeared during setup: $path"
            link "$temporary" "$path" || exit 1
        ); then
            fail "Cannot create file: $path"
        fi
        created=$((created + 1))
    }

    # Keep the EXIT trap and its download variable alive in the same scope,
    # without replacing the caller's traps or leaving cleanup until main exits.
    install_mangomagic() (
        local f=''
        cleanup_download() {
            local status=$?
            trap - EXIT
            if [ -n "$f" ]; then
                if ! rm -f -- "$f"; then
                    printf 'Cannot remove MangoMagic download: %s\n' "$f" >&2
                    [ "$status" -ne 0 ] || status=1
                fi
            fi
            exit "$status"
        }
        trap cleanup_download EXIT
        trap 'exit 130' INT
        trap 'exit 143' TERM
        command -v curl >/dev/null 2>&1 || fail 'MangoMagic setup needs curl.'
        f=$(mktemp "${TMPDIR:-/tmp}/mangomagic-install.XXXXXXXX") || fail 'Cannot create a temporary file.'
        if ! curl -fsSL https://raw.githubusercontent.com/mango-magic/mangomagic/main/install.sh -o "$f"; then
            fail 'Could not download the MangoMagic installer.'
        fi
        if [ "$no_restart" -eq 1 ]; then
            /bin/bash "$f" --no-restart || fail 'MangoMagic setup failed.'
        else
            /bin/bash "$f" || fail 'MangoMagic setup failed.'
        fi
    )

    # Validate the entire manifest before creating directories or files.
    check_directory "$destination"
'''
FOOTER = r'''
    if [ "$with_mangomagic" -eq 1 ]; then
        if ! install_mangomagic; then
            printf '\nWorkspace files remain available at: %s\n' "$destination" >&2
            printf 'Open START_HERE.md to use the workspace without MangoMagic.\n' >&2
            fail 'Combined setup incomplete. Retry with the same destination and --with-mangomagic (plus --no-restart to defer restart); existing workspace files will be preserved.'
        fi
    fi

    printf '\nAI Operations folder: %s\n' "$destination"
    printf 'Created %s file(s); preserved %s existing file(s).\n' "$created" "$preserved"
    printf '\nNext steps:\n'
    printf '1. Add this folder as a local folder project in the app.\n'
    printf '2. Paste this into that project chat (also works when START_HERE.md is from an earlier install):\n'
    printf '   Build my assistant. Read 00_Command_Centre/BUILD_MY_ASSISTANT.md and follow its workflow using my existing context and authorisation.\n'
    printf '3. Follow 00_Command_Centre/BUILD_MY_ASSISTANT.md to build your profile and check a first deliverable.\n'
    printf '4. In the new project chat, verify which project-local agent definitions the app supports.\n'
    if [ "$with_mangomagic" -eq 1 ]; then
        if [ "$no_restart" -eq 1 ]; then
            printf 'MangoMagic setup completed; ChatGPT restart pending. Quit and reopen ChatGPT before selecting MangoMagic 7.1.\n'
        else
            printf 'MangoMagic setup completed and ChatGPT restarted. Select MangoMagic 7.1 in the app.\n'
        fi
    else
        printf 'Setup copied local files only.\n'
    fi
    printf 'No workers were launched and no schedules were created.\n'
    if [ "$no_open" -eq 0 ] && [ "$(uname -s)" = Darwin ] && command -v open >/dev/null 2>&1; then
        if ! open "$destination" </dev/null; then
            printf 'Could not open Finder. Open the folder above manually.\n' >&2
        fi
    fi
}
main "$@"
'''


def render(starter):
    """Read a sorted snapshot; reject links, special files and non-text inputs."""
    if starter.is_symlink() or not starter.is_dir():
        raise ValueError("starter must be a real directory")
    files = []
    directories = set()
    for path in sorted(starter.rglob("*")):
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            raise ValueError("starter symlink refused: " + str(path))
        if stat.S_ISDIR(mode):
            continue  # Only directories required by files are shipped.
        if not stat.S_ISREG(mode):
            raise ValueError("starter special file refused: " + str(path))
        data = path.read_bytes()
        content = data.decode("utf-8")
        if b"\0" in data:
            raise ValueError("starter contains NUL bytes: " + str(path))
        relative = path.relative_to(starter).as_posix()
        files.append((relative, content, bool(mode & 0o111)))
        directories.update(parent.as_posix() for parent in Path(relative).parents if parent != Path("."))
    if not files:
        raise ValueError("starter has no text files; refusing an empty installer")

    chunks = [HEADER]
    for relative, _, _ in files:
        chunks.append("    check_file " + shlex.quote(relative) + "\n")
    chunks.append('    ensure_directory \'\'\n')
    for directory in sorted(directories, key=lambda value: (value.count("/"), value)):
        chunks.append("    ensure_directory " + shlex.quote(directory) + "\n")
    for relative, content, executable in files:
        delimiter = "OPERATIONS_DATA_" + hashlib.sha256(content.encode("utf-8")).hexdigest()
        while delimiter in content.splitlines():
            delimiter += "_"
        newline = content.endswith("\n")
        chunks.append("    write_file {} {} {} <<'{}'\n".format(
            shlex.quote(relative), int(executable), int(newline), delimiter))
        chunks.append(content)
        if content and not newline:
            chunks.append("\n")
        chunks.append(delimiter + "\n")
    chunks.append(FOOTER)
    return "".join(chunks)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--starter", type=Path, default=ROOT / "starter")
    parser.add_argument("--output", type=Path, default=ROOT / "setup-operations.sh")
    args = parser.parse_args()
    try:
        if args.output.is_symlink():
            raise ValueError("output symlink refused: " + str(args.output))
        if args.output.exists() and not args.output.is_file():
            raise ValueError("output must be a regular file: " + str(args.output))
        source = render(args.starter)
        # Never open or chmod the output path itself: a symlink introduced
        # during the build cannot redirect a write to an unrelated file.
        fd, temporary = tempfile.mkstemp(prefix=".operations-build-", dir=args.output.parent)
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(source.encode("utf-8"))
                stream.flush()
                os.fchmod(stream.fileno(), 0o755)
            if args.output.is_symlink():
                raise ValueError("output symlink refused: " + str(args.output))
            os.replace(temporary, args.output)
        finally:
            Path(temporary).unlink(missing_ok=True)
    except (OSError, UnicodeError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
